name: Publish Artifacts

on:
  push:
    tags:
      - '**'

env:
  SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
  SONATYPE_PWD: ${{ secrets.SONATYPE_PWD }}
  OSS_USER: '${{ secrets.OSS_USER }}'
  OSS_TOKEN: '${{ secrets.OSS_TOKEN }}'
  OSS_STAGING_PROFILE_ID: '${{ secrets.OSS_STAGING_PROFILE_ID }}'
  SIGNING_KEY_NAME: '${{ secrets.SIGNING_KEY_NAME }}'
  SIGNING_KEY_ID: '${{ secrets.SIGNING_KEY_ID }}'
  SIGNING_KEY_PASSPHRASE: '${{ secrets.SIGNING_KEY_PASSPHRASE }}'
  SIGNING_KEY: '${{ secrets.SIGNING_KEY }}'
  GRADLE_PUBLISH_KEY: '${{ secrets.GRADLE_PUBLISH_KEY }}'
  GRADLE_PUBLISH_SECRET: '${{ secrets.GRADLE_PUBLISH_SECRET }}'

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    outputs:
      endpoints-version: ${{ steps.get-endpoints-version.outputs.endpoints-version }}

    steps:
      - uses: actions/checkout@v3.6.0
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3.1.0
        with:
          distribution: 'adopt'
          java-version: '15'

      - name: Build and test with Gradle
        uses: gradle/gradle-build-action@v2.2.0
        with:
          arguments: build --scan --stacktrace

      - id: get-endpoints-version
        name: Get Endpoints version
        run: |
          ./gradlew
          echo "::set-output name=endpoints-version::$(head -n 1 build/semver/version.txt)"

      - name: Upload reports
        uses: actions/upload-artifact@v3.0.0
        with:
          name: 'reports-${{ matrix.os }}'
          path: '**/build/reports/**'

      - name: Stop Gradle daemons
        run: ./gradlew --stop

  publish:
    needs: build
    env:
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3.6.0

    - uses: actions/setup-java@v3.1.0
      with:
        distribution: 'adopt'
        java-version: '15'
        cache: 'gradle'

    - name: Publish alpha/beta/rc artifacts
      if: |
        contains(needs.build.outputs.endpoints-version, 'alpha') ||
        contains(needs.build.outputs.endpoints-version, 'beta') ||
        contains(needs.build.outputs.endpoints-version, 'rc')
      run: ./gradlew --full-stacktrace publishToSonatype closeAndReleaseSonatypeStagingRepository -x dokkaHtml

    - name: Publish final artifacts
      if: |
        !contains(needs.build.outputs.endpoints-version, 'alpha') &&
        !contains(needs.build.outputs.endpoints-version, 'beta') &&
        !contains(needs.build.outputs.endpoints-version, 'rc')
      run: ./gradlew --full-stacktrace publishToSonatype closeAndReleaseSonatypeStagingRepository -x dokkaHtml

    - name: Stop Gradle daemons
      run: ./gradlew --stop
