name: "Publish libraries"
on:
  push:
    branches:
      - main
jobs:
  publish:
    env:
      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      SONATYPE_PWD: ${{ secrets.SONATYPE_PWD }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_SECRET }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_PASSPHRASE }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Publish"
        run: |
          ./gradlew publish
